apiVersion: batch/v1
kind: Job
metadata:
  name: build-job
spec:
  template:
    spec:
      containers:
        - name: build
          image: node:14
          command: ["sh", "-c", "cd /workspace && npm install && npm run build"]
          volumeMounts:
            - name: workspace
              mountPath: /workspace
      restartPolicy: Never
      volumes:
        - name: workspace
          emptyDir: {}
