apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: build-job-
spec:
  entrypoint: main
  templates:
    - name: main
      steps:
        - - name: clone-repo
            template: git-clone
        - - name: build
            template: build

    - name: git-clone
      container:
        image: alpine/git
        command: ["sh", "-c"]
        args:
          [
            "git clone --branch kube https://github.com/briansunter/graph.git /workspace && cd /workspace/site",
          ]
        volumeMounts:
          - name: workspace
            mountPath: /workspace

    - name: build
      container:
        image: node:14
        command: ["sh", "-c", "cd /workspace/site && ls -R"]
        volumeMounts:
          - name: workspace
            mountPath: /workspace

  volumes:
    - name: workspace
      emptyDir: {}
