apiVersion: batch/v1
kind: Job
metadata:
  name: build-job-v3
spec:
  template:
    spec:
      containers:
        - name: build
          image: gcr.io/kaniko-project/executor:latest
          args:
            [
              "--dockerfile=/workspace/graph/site/Dockerfile",
              "--context=dir:///workspace/graph/site",
              "--destination=local-registry:5001/graph:latest",
            ]
          volumeMounts:
            - name: workspace
              mountPath: /workspace
            - name: kubeconfig
              mountPath: /root/.kube
              subPath: config
      restartPolicy: Never
      volumes:
        - name: workspace
          emptyDir: {}
        - name: kubeconfig
          configMap:
            name: kubeconfig
