apiVersion: batch/v1
kind: Job
metadata:
  name: build-job-v3
spec:
  template:
    spec:
      containers:
        - name: build
          image: docker:stable-dind
          command: [
              "sh",
              "-c",
              "apk add --no-cache git && \
              cd /workspace && \
              git clone https://github.com/briansunter/graph.git && \
              docker build -t local-registry:5001/graph:latest . && \
              docker push local-registry:5001/graph:latest && \
              kubectl rollout restart deployment/nginx-deployment",
            ]
          volumeMounts:
            - name: workspace
              mountPath: /workspace
      restartPolicy: Never
      volumes:
        - name: workspace
          emptyDir: {}
