apiVersion: batch/v1
kind: Job
metadata:
  name: build-job-v2 # Change the job name to a new one
spec:
  template:
    spec:
      containers:
        - name: build
          image: node:18
          command:
            [
              "sh",
              "-c",
              "cd /workspace && git clone https://github.com/briansunter/graph.git && cd graph/site && npm install && npm run build",
            ]
          volumeMounts:
            - name: workspace
              mountPath: /workspace
      restartPolicy: Never
      volumes:
        - name: workspace
          emptyDir: {}
