apiVersion: batch/v1
kind: Job
metadata:
  name: build-job-v2
spec:
  template:
    spec:
      containers:
        - name: build
          image: docker:stable-dind
          command: [
              "sh",
              "-c",
              "cd /workspace && \
              git clone https://github.com/briansunter/graph.git && \
              cd graph/site && \
              npm install && \
              npx playwright install-deps && \
              npx playwright install && \
              npm run build && \
              docker build -t local-registry:5001/graph:latest . && \
              docker push local-registry:5001/graph:latest && \
              kubectl rollout restart deployment/nginx-deployment",
            ]
          volumeMounts:
            - name: workspace
              mountPath: /workspace
            - name: kubeconfig
              mountPath: /root/.kube
              subPath: config
      restartPolicy: Never
      volumes:
        - name: workspace
          emptyDir: {}
        - name: kubeconfig
          configMap:
            name: kubeconfig
