apiVersion: batch/v1
kind: Job
metadata:
  name: build-job-v3
spec:
  template:
    spec:
      containers:
        - name: build
          image: gcr.io/kaniko-project/executor:latest
          args:
            [
              "--dockerfile=Dockerfile",
              "--context=git://github.com/briansunter/graph.git#refs/heads/kube",
              "--destination=briansunter/site:latest",
            ]
          securityContext:
            privileged: true
          volumeMounts:
            - name: docker-config
              mountPath: /kaniko/.docker
      restartPolicy: Never
      volumes:
        - name: docker-config
          secret:
            secretName: docker-config
