apiVersion: batch/v1
kind: Job
metadata:
  name: build-job-v3
spec:
  template:
    spec:
      containers:
        - name: build
          image: gcr.io/kaniko-project/executor:latest
          args:
            [
              "--dockerfile=Dockerfile",
              "--context=git://github.com/briansunter/graph.git#refs/heads/kube",
              "--destination=harbor.bsunter.net/graph:latest",
              "--insecure",
            ]
          volumeMounts:
            - name: kaniko-secret
              mountPath: /kaniko/.docker
          securityContext:
            privileged: true
      restartPolicy: Never
      volumes:
        - name: kaniko-secret
          secret:
            secretName: kaniko-secret
            items:
              - key: .dockerconfigjson
                path: config.json
