apiVersion: batch/v1
kind: Job
metadata:
  name: build-job-v2
spec:
  template:
    spec:
      containers:
        - name: build
          image: node:18
          command: [
              "sh",
              "-c",
              "cd /workspace && \
              git clone https://github.com/briansunter/graph.git && \
              cd graph/site && \
              npx playwright install-deps && \
              npm install && \
              npx playwright install && \
              npm run build",
            ]
          volumeMounts:
            - name: workspace
              mountPath: /workspace
      restartPolicy: Never
      volumes:
        - name: workspace
          emptyDir: {}
