apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-cm
  namespace: argocd
data:
  repositories: |
    - url: http://host.docker.internal:5001
      name: my-insecure-registry
      insecure: true
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
        - name: nginx
          image: host.docker.internal:5001/graph:latest
          volumeMounts:
            - name: dist
              mountPath: /usr/share/nginx/html
            - name: kaniko-secret
              mountPath: /kaniko/.docker
          securityContext:
            privileged: true
      restartPolicy: Always
      volumes:
        - name: dist
          emptyDir: {}
        - name: kaniko-secret
          secret:
            secretName: regcred
            items:
              - key: .dockerconfigjson
                path: config.json
      imagePullSecrets:
        - name: regcred
